In [91]:
# Importation des bibliothÃ¨ques Python
import pandas as pd

# Chargement du dataset
# data = pd.read_fwf("imports-85.data")
data = pd.read_csv("car_data.csv", delimiter=';', header=None)
data

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [92]:
df = pd.read_csv('./imports-85.data', header=None, names=['symboling', 'normalized-losses', 'make', 'fuel-type', 'aspiration', 'num-of-doors', 'body-style', 'drive-wheels', 'engine-location', 'wheel-base', 'length', 'width', 'curb-weight', 'engine-type', 'num-of-cylinders', 'engine-size', 'fuel-system', 'bore', 'stroke', 'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg', 'highway-mpg', 'price'])
df

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3;?;alfa-romero;gas;std;two;convertible;rwd;fr...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3;?;alfa-romero;gas;std;two;convertible;rwd;fr...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1;?;alfa-romero;gas;std;two;hatchback;rwd;fron...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2;164;audi;gas;std;four;sedan;fwd;front;99.80;...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2;164;audi;gas;std;four;sedan;4wd;front;99.40;...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1;95;volvo;gas;std;four;sedan;rwd;front;109.1...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201,-1;95;volvo;gas;turbo;four;sedan;rwd;front;109...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
202,-1;95;volvo;gas;std;four;sedan;rwd;front;109.1...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203,-1;95;volvo;diesel;turbo;four;sedan;rwd;front;...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
204,-1;95;volvo;gas;turbo;four;sedan;rwd;front;109...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Test de FromModel et SelectKBest

In [93]:
from sklearn.datasets import fetch_california_housing
dataset = fetch_california_housing(as_frame=True)
#description du dataset 
print(dataset.DESCR)

.. _california_housing_dataset:

California Housing dataset
--------------------------

**Data Set Characteristics:**

    :Number of Instances: 20640

    :Number of Attributes: 8 numeric, predictive attributes and the target

    :Attribute Information:
        - MedInc        median income in block group
        - HouseAge      median house age in block group
        - AveRooms      average number of rooms per household
        - AveBedrms     average number of bedrooms per household
        - Population    block group population
        - AveOccup      average number of household members
        - Latitude      block group latitude
        - Longitude     block group longitude

    :Missing Attribute Values: None

This dataset was obtained from the StatLib repository.
https://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html

The target variable is the median house value for California districts,
expressed in hundreds of thousands of dollars ($100,000).

This dataset was derived from the 1990 U.S. census, using one row per census
block group. A block group is the smallest geographical unit for which the U.S.
Census Bureau publishes sample data (a block group typically has a population
of 600 to 3,000 people).

An household is a group of people residing within a home. Since the average
number of rooms and bedrooms in this dataset are provided per household, these
columns may take surpinsingly large values for block groups with few households
and many empty houses, such as vacation resorts.

It can be downloaded/loaded using the
:func:`sklearn.datasets.fetch_california_housing` function.

.. topic:: References

    - Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,
      Statistics and Probability Letters, 33 (1997) 291-297

In [94]:
# Importation librairies
from sklearn.feature_selection import SelectFromModel
from sklearn.linear_model import LinearRegression
import numpy as np 
import pandas as pd

In [95]:
# crÃ©ation dataset
df = pd.DataFrame(dataset.data, columns=dataset.feature_names)

# crÃ©er une colonne prix
df['MedHouseVal'] = dataset.target

# affichage dataset
df

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894

In [96]:
X = dataset.data
y = df['MedHouseVal']

In [97]:
# CrÃ©ation du sÃ©lecteur
selector = SelectFromModel(LinearRegression())

# Ajustement du sÃ©lecteur aux donnÃ©es
selector.fit(X, y)

SelectFromModel(estimator=LinearRegression())

In [99]:
# 
selector.get_support()

array([ True, False, False,  True, False, False,  True,  True])

In [109]:
# 
selector.get_params()

{'estimator__copy_X': True,
 'estimator__fit_intercept': True,
 'estimator__n_jobs': None,
 'estimator__normalize': 'deprecated',
 'estimator__positive': False,
 'estimator': LinearRegression(),
 'importance_getter': 'auto',
 'max_features': None,
 'norm_order': 1,
 'prefit': False,
 'threshold': None}

In [100]:
# RÃ©cupÃ©ration des features (colonnes) les plus importantes
selector.get_feature_names_out()

array(['MedInc', 'AveBedrms', 'Latitude', 'Longitude'], dtype=object)

In [101]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X[['MedInc', 'AveBedrms', 'Latitude', 'Longitude']], y, test_size= 0.2, random_state= 42)

In [102]:
# CrÃ©ation modÃ¨le de regression linÃ©aire
lmodellineaire = LinearRegression()

# Entrainement du modÃ¨le
lmodellineaire.fit(X_train, y_train)

LinearRegression()

In [106]:
# train evaluate
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

y_pred = lmodellineaire.predict(X_test) # code ici

# Calcul de l'erreur absolue moyenne
mae = mean_absolute_error(y_test, y_pred)
print("Erreur mae = {}".format(mae))

# Calcul de l'erreur quadratique moyenne (mse)
mse = mean_squared_error(y_test, y_pred)
print("Erreur mse = {}".format(mse))

# Calcul de l'erreur rmse
rmse = mean_squared_error(y_test, y_pred, squared=False) # code ici 
print("Erreur rmse = {}".format(rmse))

# Calcul de RÂ²
r2 = r2_score(y_test, y_pred) # code ici 
print("RÂ² = {}".format(r2))

Erreur mae = 0.5451529556617896
Erreur mse = 0.562699630959292
Erreur rmse = 0.7501330755001355
RÂ² = 0.5705923568116398

### Avec toutes les variables

In [115]:
# SÃ©paration en trainset et testset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state= 42)

# Ajustement du modÃ¨le
lmodellineaire.fit(X_train, y_train)

# PrÃ©diction
y_pred = lmodellineaire.predict(X_test) # code ici

# Calcul de l'erreur absolue moyenne
mae = mean_absolute_error(y_test, y_pred)
print("Erreur mae = {}".format(mae))

# Calcul de l'erreur quadratique moyenne (mse)
mse = mean_squared_error(y_test, y_pred)
print("Erreur mse = {}".format(mse))

# Calcul de l'erreur rmse
rmse = mean_squared_error(y_test, y_pred, squared=False) # code ici 
print("Erreur rmse = {}".format(rmse))

# Calcul de RÂ²
r2 = r2_score(y_test, y_pred) # code ici 
print("RÂ² = {}".format(r2))

Erreur mae = 0.5332001304956556
Erreur mse = 0.5558915986952443
Erreur rmse = 0.7455813830127763
RÂ² = 0.5757877060324508

### GridSearchCV

In [107]:
from sklearn.model_selection import GridSearchCV

In [116]:
param_grid = {
    'fit_intercept':[True,False],
    'normalize':[True,False],
    'copy_X':[True, False]
}

gridLR = GridSearchCV(estimator=LinearRegression(), param_grid = param_grid, cv = 3, n_jobs=-1)
gridLR.fit(X_train, y_train)

print(" Results from Grid Search " )
print("\n The best estimator across ALL searched params:\n",gridLR.best_estimator_)
print("\n The best score across ALL searched params:\n",gridLR.best_score_)
print("\n The best parameters across ALL searched params:\n",gridLR.best_params_)

 Results from Grid Search

 The best estimator across ALL searched params:
 LinearRegression(normalize=True)

 The best score across ALL searched params:
 0.6110921251096775

 The best parameters across ALL searched params:
 {'copy_X': True, 'fit_intercept': True, 'normalize': True}

c:\Users\AxelArcidiaco\anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  warnings.warn(